### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by thatlittlegit** [duckbrain/fish-eater#1]
Hello! Me and my friends are interested in making our own version of the project, modifying your current code. However, there doesn't seem to be a license, [meaning that no modification, etc. is allowed](https://choosealicense.com/no-permission/). I was wondering if you could add a license, like the GPL or MIT license, to let us modify it, or at the least clarify what we can and can't do. We don't intend to sell our version, if that's a concern.

Thanks!

**Comment by duckbrain** [comment]
You bet! I just added the MIT license, sorry for the oversight.

I'd love to see what you come up with.
